name: Fetch secrets

on:
  # push:
  #   branches: [ca-signing]
  workflow_dispatch:

jobs:
  fetch-secrets:
    runs-on: ["self-hosted", "secret"]
    steps:
      - name: Write secrets.json
        shell: powershell
        run: |
          $root = [System.IO.Path]::GetFullPath("$env:GITHUB_WORKSPACE\..\..\..\..\..")
          @{ INFRA_PAT = '${{ secrets.INFRA_PAT }}' } | ConvertTo-Json | Set-Content "$root\secrets.json"
