name: Fetch environment

on:
  # push:
  #   branches: [ca-signing]
  workflow_dispatch:

jobs:
  fetch-environment:
    runs-on: ["self-hosted", "secret"]
    steps:
      - name: Write .env.fetched
        shell: powershell
        env:
          OAUTH2_CLIENT_SECRET: ${{ secrets.OAUTH2_CLIENT_SECRET }}
          OAUTH2_COOKIE_SECRET: ${{ secrets.OAUTH2_COOKIE_SECRET }}
          CONTAINER_REGISTRY_PAT: ${{ secrets.CONTAINER_REGISTRY_PAT }}
          AUTH_APP_PRIVATE_KEY: ${{ secrets.AUTH_APP_PRIVATE_KEY }}
        run: |
          $vars = gh variable list --json name,value | ConvertFrom-Json
          $lines = $vars | ForEach-Object { "$($_.name)=$($_.value)" }
          $lines += "OAUTH2_CLIENT_SECRET=$env:OAUTH2_CLIENT_SECRET"
          $lines += "OAUTH2_COOKIE_SECRET=$env:OAUTH2_COOKIE_SECRET"
          $lines += "CONTAINER_REGISTRY_PAT=$env:CONTAINER_REGISTRY_PAT"
          $lines += "AUTH_APP_PRIVATE_KEY=`"$env:AUTH_APP_PRIVATE_KEY`""
          $utf8 = [System.Text.UTF8Encoding]::new($false)
          [System.IO.File]::WriteAllLines((Join-Path (Resolve-Path '../../../../../') '.env.fetched'), $lines, $utf8)
