name: Fetch secrets

on:
  workflow_dispatch:

jobs:
  fetch-secrets:
    runs-on: ["self-hosted", "secret"]
    steps:
      - name: Write secrets.json
        run: |
          echo '{"INFRA_PAT":"${{ secrets.INFRA_PAT }}"}' > secrets.json
