name: Fetch secrets

on:
  # push:
  #   branches: [ca-signing]
  workflow_dispatch:

jobs:
  fetch-secrets:
    runs-on: ["self-hosted", "secret"]
    steps:
      - name: Write secrets.json
        run: |
          echo '{"INFRA_PAT":"${{ secrets.INFRA_PAT }}"}' > ../../../../../secrets.json
